language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - cmake
      - libssl-dev
      - libc6-dev
      - zlib1g-dev
before_install:
  - mkdir Debug
  - cmake -D CMAKE_BUILD_TYPE=Debug ..
