version: '3'
services:
  sys:
    build:
      context: .
      dockerfile: Dockerfile.run
    image: phusion/baseimage
    stdin_open: true
    tty: true
    command: /bin/bash
    links:
      - database
  database:
    image: library/mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: ubuntu:rolling
    volumes:
      - .:/home/libnss-maria
    stdin_open: true
    tty: true
    command: /bin/bash
